"""Models for delayed release of generated elements."""

from __future__ import annotations

from dataclasses import dataclass
from math import isfinite
from typing import Protocol

from liiontr.chemistry.elements import (
    ElementInventory,
)


class ElementReleaseModel(Protocol):
    """Define the interface for elemental release models."""

    def release_rates(
        self,
        stored_inventory: ElementInventory,
    ) -> dict[str, float]:
        """Return elemental release rates in mol/s."""
        ...

@dataclass(slots=True, frozen=True)
class FirstOrderElementReleaseModel:
    """Represent first-order internal element release.

    The model represents transport of reaction products from an
    internal condensed or porous reservoir to the gas volume used
    for pressure and venting calculations.

    For each element, the release rate is

        dn_release / dt = n_pending / tau

    where ``n_pending`` is the amount generated by reactions but not
    yet transferred to the gas volume, and ``tau`` is the
    characteristic internal release time.

    The time constant is an effective reduced-order transport
    parameter. It may represent combined effects of porous transport,
    pressure-driven flow, diffusion, permeation, vaporization,
    redistribution through the cell, and access to the vent path.

    It should therefore not be interpreted as a molecular-diffusion
    time constant unless such an interpretation is independently
    justified by a more detailed transport model or experimental
    calibration.

    Parameters
    ----------
    time_constant : float
        Characteristic internal release time in seconds.
    """

    time_constant: float

    def __post_init__(self) -> None:
        """Validate the release model."""
        if (
            not isfinite(self.time_constant)
            or self.time_constant <= 0.0
        ):
            raise ValueError(
                "Release time constant must be finite "
                "and greater than zero."
            )

    def release_rates(
        self,
        stored_inventory: ElementInventory,
    ) -> dict[str, float]:
        """Return elemental release rates in mol/s."""
        return {
            element_name: (
                amount / self.time_constant
            )
            for element_name, amount
            in stored_inventory.moles.items()
        }