"""Element generation scaled by reaction heat release."""

from __future__ import annotations

from dataclasses import dataclass
from math import isfinite

from liiontr.chemistry.elements import (
    ElementInventory,
)


@dataclass(frozen=True, slots=True)
class EnergyScaledElementGenerationModel:
    """Scale total elemental gas production with reaction energy."""

    element_yields_per_cell_mass: dict[str, float]
    reference_reaction_energy_per_cell_mass: float

    def __post_init__(self) -> None:
        """Validate the element-generation model."""
        if (
            not isfinite(
                self.reference_reaction_energy_per_cell_mass
            )
            or self.reference_reaction_energy_per_cell_mass
            <= 0.0
        ):
            raise ValueError(
                "Reference reaction energy per cell mass "
                "must be finite and greater than zero."
            )

        if not self.element_yields_per_cell_mass:
            raise ValueError(
                "At least one elemental yield is required."
            )

        for element_name, amount in (
            self.element_yields_per_cell_mass.items()
        ):
            if not element_name:
                raise ValueError(
                    "Element names must not be empty."
                )

            if not isfinite(amount) or amount < 0.0:
                raise ValueError(
                    "Element yields must be finite "
                    "and nonnegative."
                )

    @property
    def element_names(self) -> list[str]:
        """Return element names in deterministic order."""
        return list(
            self.element_yields_per_cell_mass
        )

    def generation_progress(
        self,
        released_reaction_energy: float,
        cell_mass: float,
    ) -> float:
        """Return the bounded aggregate gas-generation progress."""
        if not isfinite(released_reaction_energy):
            raise ValueError("Released reaction energy must be finite.")

        if released_reaction_energy < 0.0:
            raise ValueError(
                "Released reaction energy must be greater than or equal to zero."
            )

        if not isfinite(cell_mass) or cell_mass <= 0.0:
            raise ValueError("Cell mass must be finite and greater than zero.")

        reference_energy = self.reference_reaction_energy_per_cell_mass * cell_mass

        progress = released_reaction_energy / reference_energy

        return min(
            max(
                progress,
                0.0,
            ),
            1.0,
        )

    def generation_rates(
        self,
        heat_generation: float,
    ) -> dict[str, float]:
        """Return elemental generation rates in mol/s."""
        if (
            not isfinite(heat_generation)
            or heat_generation < 0.0
        ):
            raise ValueError(
                "Heat generation must be finite "
                "and nonnegative."
            )

        equivalent_cell_mass_rate = (
            heat_generation
            / self.reference_reaction_energy_per_cell_mass
        )

        return {
            element_name: (
                element_yield
                * equivalent_cell_mass_rate
            )
            for element_name, element_yield
            in self.element_yields_per_cell_mass.items()
        }

    def generated_inventory(
        self,
        released_reaction_energy: float,
        cell_mass: float,
    ) -> ElementInventory:
        """Return inventory generated by cumulative reaction energy."""
        if (
            not isfinite(released_reaction_energy)
            or released_reaction_energy < 0.0
        ):
            raise ValueError(
                "Released reaction energy must be finite "
                "and nonnegative."
            )

        if not isfinite(cell_mass) or cell_mass <= 0.0:
            raise ValueError(
                "Cell mass must be finite "
                "and greater than zero."
            )

        progress = self.generation_progress(
            released_reaction_energy=(released_reaction_energy),
            cell_mass=cell_mass,
        )

        return ElementInventory(
            moles={
                element_name: (
                    element_yield
                    * cell_mass
                    * progress
                )
                for element_name, element_yield
                in self.element_yields_per_cell_mass.items()
            }
        )