from __future__ import annotations

import math
from dataclasses import dataclass


R = 8.314462618


@dataclass(slots=True)
class Reaction:
    """
    Single thermal runaway reaction.

    Arrhenius model:

        rate = A exp(-Ea/RT)

    Heat generation:

        q = dH * rate
    """

    name: str

    activation_energy: float

    pre_exponential_factor: float

    enthalpy: float

    def rate(
        self,
        temperature: float,
    ) -> float:
        """
        Reaction rate.
        """

        return self.pre_exponential_factor * math.exp(
            -self.activation_energy / (R * temperature)
        )

    def heat_generation(
        self,
        temperature: float,
    ) -> float:
        """
        Heat generated by this reaction.
        """

        return self.enthalpy * self.rate(temperature)
